# -*- coding: utf-8 -*-
"""attendance-nba-api.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_T8LBCY1js3ELZ9MAgsQC_eSupXrKhdg
"""

# pip install nba_api

from nba_api.stats.static import teams

nba_teams = teams.get_teams()

rockets = [team for team in nba_teams if team['abbreviation'] == 'HOU'][0]
rockets_id = rockets['id']
rockets

from nba_api.stats.endpoints import leaguegamefinder
import pandas as pd

# Query for games where the Rockets were playing
gamefinder = leaguegamefinder.LeagueGameFinder(team_id_nullable=rockets_id)

games = gamefinder.get_data_frames()[0]
games['GAME_DATE'] = pd.to_datetime(games['GAME_DATE'], format = "%Y-%m-%d")
games_23 = games[(games['GAME_DATE'] >= "2023-10-25") & (games['GAME_DATE'] <= "2025-04-06")]
game_ids = list(games_23['GAME_ID'])
games_23

from nba_api.stats.endpoints import boxscoresummaryv2

game_attendance = pd.DataFrame(columns = ['GAME_DATE', 'ATTENDANCE'])
for game in game_ids:
  print(game)
  attendance = boxscoresummaryv2.BoxScoreSummaryV2(game_id = game)
  attendance = attendance.get_data_frames()[4]
  game_attendance = pd.concat([game_attendance, attendance[['GAME_DATE', 'ATTENDANCE']]])

game_attendance.head()

