---
title: "531_final"
author: "Nick Kim"
date: "2025-03-23"
output: pdf_document
---

```{r}
library(readxl)
draft_dat <- read.csv("/Users/nicholaskim/Documents/STAT-531/final/data/draft_history.csv")
matchups <- read_excel("/Users/nicholaskim/Documents/STAT-531/final/data/matchups.xlsx")
```

```{r}
library(dplyr)
draft_dat[draft_dat$round_number==1,] %>% 
  filter(team_id==1610612745) %>% 
  filter(season >= 2021) %>% 
  group_by(team_id,season) %>% 
  summarise(Total = sum(round_number))
```

```{r}
team_ids <- unique(draft_dat[draft_dat$season>=2020,c(8,10)])
```

```{r}
update_elo <- function(rating1, rating2, result, K = 20) {
  E1 <- 1 / (1 + 10^((rating2 - rating1) / 400))  # Expected score for team 1
  E2 <- 1 / (1 + 10^((rating1 - rating2) / 400))  # Expected score for team 2
  
  if (result == 1) {  # Team 1 wins
    rating1_new <- rating1 + K * (1 - E1)
    rating2_new <- rating2 + K * (0 - E2)
  } else {  # Team 2 wins
    rating1_new <- rating1 + K * (0 - E1)
    rating2_new <- rating2 + K * (1 - E2)
    
  } 
  
  return(c(rating1_new, rating2_new))
}
```


```{r}
update_elo(elo_ratings[1,2],elo_ratings[2,2],1)
```

```{r}
# Initialize Elo ratings correctly
elo_ratings <- data.frame(Team = unique(c(matchups$Visitor, matchups$Home)),
                          Elo = rep(1500, length(unique(c(matchups$Visitor, matchups$Home)))))

# Compute game results
matchups$Result <- ifelse(matchups$PTS_V > matchups$PTS_H, 1, 2)  

elo_v <- c()
elo_h <- c()

# Loop through matchups to update Elo ratings
for (i in 1:nrow(matchups)) {
  team1 <- matchups$Visitor[i]
  team2 <- matchups$Home[i]
  
  # Get current ratings using match()
  rating1 <- elo_ratings$Elo[match(team1, elo_ratings$Team)]
  rating2 <- elo_ratings$Elo[match(team2, elo_ratings$Team)]
  
  # Update Elo ratings
  updated_ratings <- update_elo(rating1, rating2, matchups$Result[i])
  
  # Save updated ratings back into the data frame
  elo_ratings$Elo[elo_ratings$Team == team1] <- updated_ratings[1]
  elo_ratings$Elo[elo_ratings$Team == team2] <- updated_ratings[2]
  
  elo_v <- c(elo_v,updated_ratings[1])
  elo_h <- c(elo_h,updated_ratings[2])
  
}

matchups$ELO_V <- elo_v
matchups$ELO_H <- elo_h
```

```{r}
rockets_matchups<-matchups[(matchups$Visitor=="Houston Rockets")|(matchups$Home=="Houston Rockets"),]
rockets_matchups
```
```{r}
n <- nrow(r_23)
rockets_elo_df <- data.frame(date = as.Date(rep(NA, n)), elo = rep(NA, n))
row_counter <- 1

for (i in 1:n) {
  if (r_23[i, 3] == "Houston Rockets") {
    rockets_elo_df[row_counter, ] <- list(as.Date(r_23[[i, 2]],format = "%a, %b %d, %Y"), as.numeric(r_23[i, 9]))
    row_counter <- row_counter + 1
  } else if (r_23[i, 5] == "Houston Rockets") {
    rockets_elo_df[row_counter, ] <- list(as.Date(r_23[[i, 2]],format = "%a, %b %d, %Y"), as.numeric(r_23[i, 10]))
    row_counter <- row_counter + 1
  }
}

# Remove unused rows
rockets_elo_df <- rockets_elo_df[1:(row_counter - 1), ]

```

```{r}
library(ggplot2)

ggplot(rockets_elo_df,aes(date,elo))+geom_line()
```
```{r}
length(diff(log(rockets_elo_df$elo)))
```

```{r}
bpm <- read_excel("/Users/nicholaskim/Documents/STAT-531/final/data/BPM.xls")

bpm["elo"] <- rockets_elo_df$elo

mod<-lm(elo ~ `Total BPM`+Home+`Last 5 Games BPM`, data = bpm)
bpm["fitted"] <- mod$fitted.values

ggplot(bpm,aes(x=Date,y=elo))+geom_point()+
  geom_line(aes(y=fitted))
```

